version: "3"

services:
  http:
    image: nginx
    environment:
    - NGINX_PORT=80
    volumes:
    - ./html:/usr/share/nginx/html
    ports:
    - "8080:80"

  websocket:
    build: 
      context: ./websocket
      dockerfile: Dockerfile
    environment:
    - PORT=3000
    volumes:
    - ./websocket/app:/app
    ports:
    - "3000:3000"
